# Generated by Django 4.2.5 on 2023-10-05 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='popular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Title', models.CharField(max_length=150)),
                ('Book_Author', models.CharField(max_length=150)),
                ('Image_URL_M', models.URLField()),
                ('num_ratings', models.IntegerField()),
                ('avg_rating', models.DecimalField(decimal_places=10, max_digits=30)),
            ],
        ),
    ]
