# Generated by Django 3.2.7 on 2024-01-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='popular',
        ),
    ]
